### ISSUE TITLE
Kudos and a few questions

### ISSUE THREAD

**Issue by 34r7h** [Gozala/protocol#4]
Really cool model to think about. I def don't grasp it yet. I think it's similar to a token protocol i'm developing that provides type definitions and extensions but maybe totally different.

* Is this repo for instantiating entities based on a sequential chain of functions, instead of an object model? 
* Does each sequential function in the chain itself be a protocol that returns a function to continue?
* Time flies. Has your thought or implementation on the subject evolved? link if published, plz

**Comment by Gozala** [comment]
>     * Is this repo for instantiating entities based on a sequential chain of functions, instead of an object model?

I'm not sure I fully understand the question, here but generally speaking idea is to allow defining generic interface definition and supply for specific types (or classes) separately. This enables type / class specific implementations to be created without having to coordinate with an interface / protocol definition.

It is really just JS variant of Clojure protocols & I think this is really good explanation of both problem and solution that Clojure developed https://vimeo.com/11236603

> Does each sequential function in the chain itself be a protocol that returns a function to continue?

Again not sure what you mean exactly but from the example in the readme `Sequential` is just an object with three functions `first`, `rest` and `join`. Which just wrap a switch statement that delegates to `Object.prototypeOf(args[0])[methodId](...args)`.

Actual delegation is bit more complicated (it needs to deal with primitive types etc...) but in nutshell protocol functions delegate to a function that were later implemented for type.

> Time flies. Has your thought or implementation on the subject evolved? link if published, plz

After using this for a bit, I recognized that:

1. Clustering functions was not really providing much value just complicated API.
2. It was way too easy to get duplicate dependencies in node_modules which lead to different function IDs been generate across them. In turn that caused some deps to see protocol implementations and others not.

I have attempted above two issues with https://github.com/Gozala/method 

Later on I came to appreciate type systems and [Elm](https://elm-lang.org/)s intentional design to not use generics, in favor of just using `List.map` when dealing with lists and `Dict.map` when working with dictionaries. While it certainly adds bit more boilerplate and sacrifices some extensibility, it definitely make understanding code easier as reader can tell exactly what is been called as opposed to inferring it from arguments.

I hope this helps.

**Comment by 34r7h** [comment]
Thanks for the in-depth response and links. It seems protocol-oriented
programming should comply with group theory proofs to guarantee
non-blocking and error-free functionality. Very useful concepts for me atm.
I'm stitching together a token protocol with the goal of running
turing-complete compute without current smart contracts. So, I'm willing to
trade difficulty understanding for precision.

I'll study more. Thank you again and good luck with keeping a flow!
